In [1]:
import geopandas as gpd

In [9]:
gdf = gpd.read_file("../usda_ofm.gpkg")
gdf

,listing_id,update_time,listing_name,location_address,orgnization,orgnization_1,orgnization_2,orgnization_3,orgnization_4,orgnization_888,...,FUNCSTAT,COUNTYCC,AREALAND,AREAWATER,OBJECTID,CENTLAT,CENTLON,INTPTLAT,INTPTLON,geometry
0,700281,2014-08-27 17:08:09,Lund Produce Co. Branchgrove Farms,"15906 County Line Rd., Elgin, Texas 78621",None,NaN,NaN,NaN,NaN,NaN,...,A,H1,2575299585,79506870,2420,+30.3343599,-097.7818171,+30.2395263,-097.6910527,POINT (-97.39061 30.39482)
1,700326,2014-09-16 14:37:47,Coyote Creek Organic Farm and Feed Mill,"13817 Klaus Lane, Elgin, Texas 78621",None,NaN,NaN,NaN,NaN,NaN,...,A,H1,2575299585,79506870,2420,+30.3343599,-097.7818171,+30.2395263,-097.6910527,POINT (-97.42852 30.36198)
2,700478,2014-07-29 22:34:32,Henrietta Creek Orchard,"14255 Old Denton Road, Roanoke, Texas 76262",None,NaN,NaN,NaN,NaN,NaN,...,A,H1,2241376178,99392439,2656,+32.7718353,-097.2911316,+32.7721191,-097.2912241,POINT (-97.2976 32.98628)
3,700602,2015-03-26 13:51:23,Partybarn Farm,"18611 Becker Rd, Hockley, Texas 77447",None,NaN,NaN,NaN,NaN,NaN,...,A,H1,4421991136,180517819,2814,+29.8573332,-095.3920016,+29.8572730,-095.3930371,POINT (-95.79998 30.04583)
4,700830,2014-08-12 20:17:00,Munkebo Farm,"20826 Blake Manor Rd., Manor, Texas 78653",None,NaN,NaN,NaN,NaN,NaN,...,A,H1,2575299585,79506870,2420,+30.3343599,-097.7818171,+30.2395263,-097.6910527,POINT (-97.48275 30.26182)
5,701314,2016-02-06 02:38:36,Honey's Acres Farm,"1350 Stoney Creek Dr, Cedar Hill, Texas 75104",None,NaN,NaN,NaN,NaN,NaN,...,A,H1,2261553244,91821724,1563,+32.7664847,-096.7777649,+32.7669866,-096.7784238,POINT (-96.93754 32.56125)
6,701486,2023-08-12 09:33:22,Hope Farms Market,"10401 Scott Street, Houston , Texas 77051",TOFGA;Slow Flowers;,0.0,0.0,1.0,0.0,1.0,...,A,H1,4421991136,180517819,2814,+29.8573332,-095.3920016,+29.8572730,-095.3930371,POINT (-95.36759 29.64558)
7,702066,2025-05-20 17:32:22,Nava Farms,"4708 E Hwy 71, Del Valle, TX, USA",None,0.0,0.0,0.0,0.0,0.0,...,A,H1,2575299585,79506870,2420,+30.3343599,-097.7818171,+30.2395263,-097.6910527,POINT (-97.59305 30.18739)
8,704529,None,Homestead Farms,"4160 Keller Hicks Road, Keller, TX 76244",None,0.0,0.0,0.0,0.0,0.0,...,A,H1,2241376178,99392439,2656,+32.7718353,-097.2911316,+32.7721191,-097.2912241,POINT (-97.27278 32.93613)
9,704544,None,Mars Hill Farm,"1604 Mars Road, Ferris, TX 75125",None,0.0,0.0,0.0,0.0,0.0,...,A,H1,2261553244,91821724,1563,+32.7664847,-096.7777649,+32.7669866,-096.7784238,POINT (-96.63766 32.58755)
10,704546,None,Neals Berry Farm and Farmers Market,"21104 Binford Road, Waller, TX 77484",None,NaN,NaN,NaN,NaN,NaN,...,A,H1,4421991136,180517819,2814,+29.8573332,-095.3920016,+29.8572730,-095.3930371,POINT (-95.8917 30.08009)
11,704549,None,Pemberton's Garden,"717 Pemberton Street, Fort Worth, TX 76108",None,0.0,0.0,0.0,0.0,0.0,...,A,H1,2241376178,99392439,2656,+32.7718353,-097.2911316,+32.7721191,-097.2912241,POINT (-97.46579 32.75141)
12,704560,None,Star Creek Country,"23702 Old Ferry Rd, Spicewood, TX 78669",None,0.0,0.0,0.0,0.0,0.0,...,A,H1,2575299585,79506870,2420,+30.3343599,-097.7818171,+30.2395263,-097.6910527,POINT (-98.06629 30.4181)
13,704573,None,Wahl's Peaches and Vegetables,15371 Hwy. 290 E.,None,0.0,0.0,0.0,0.0,0.0,...,A,H1,4421991136,180517819,2814,+29.8573332,-095.3920016,+29.8572730,-095.3930371,POINT (-95.47827 29.81471)

In [4]:
gdf.columns

Index(['listing_id', 'update_time', 'listing_name', 'location_address',
       'orgnization', 'orgnization_1', 'orgnization_2', 'orgnization_3',
       'orgnization_4', 'orgnization_888',
       ...
       'FUNCSTAT', 'COUNTYCC', 'AREALAND', 'AREAWATER', 'OBJECTID', 'CENTLAT',
       'CENTLON', 'INTPTLAT', 'INTPTLON', 'geometry'],
      dtype='object', length=284)

In [5]:
for col in gdf.columns:
    print(col)

listing_id
update_time
listing_name
location_address
orgnization
orgnization_1
orgnization_2
orgnization_3
orgnization_4
orgnization_888
orgnization_1_desc
orgnization_2_desc
orgnization_3_desc
orgnization_4_desc
orgnization_other_desc
num_supplyfarms
continueoperate_year
continue_operation_year_cyear
listing_desc
location_x
location_y
location_desc
season_month_start
season_month_end
season_weeks
season_desc
season_month
season_month_1
season_month_2
season_month_3
season_month_4
season_month_5
season_month_6
season_month_7
season_month_8
season_month_9
season_month_10
season_month_11
season_month_12
products
products_1
products_2
products_3
products_5
products_6
products_8
products_9
products_10
products_11
products_12
products_13
products_14
products_16
products_17
products_18
products_19
products_21
products_22
products_23
products_25
products_26
products_27
products_29
products_30
products_888
product_fruit
product_fruit_1
product_fruit_2
product_fruit_3
product_fruit_4
product_fruit_5
product_fruit_6
product_fruit_7
product_fruit_8
product_fruit_9
product_fruit_10
product_fruit_11
product_fruit_12
product_fruit_13
product_fruit_14
product_fruit_15
product_fruit_16
product_fruit_17
product_fruit_18
product_fruit_19
product_fruit_20
product_fruit_21
product_fruit_22
product_fruit_23
product_fruit_24
product_fruit_25
product_fruit_26
product_fruit_888
product_fruit_otherdesc
product_vegetables
product_vegetables_1
product_vegetables_2
product_vegetables_3
product_vegetables_4
product_vegetables_5
product_vegetables_6
product_vegetables_7
product_vegetables_8
product_vegetables_9
product_vegetables_10
product_vegetables_11
product_vegetables_12
product_vegetables_13
product_vegetables_14
product_vegetables_15
product_vegetables_16
product_vegetables_17
product_vegetables_18
product_vegetables_19
product_vegetables_20
product_vegetables_21
product_vegetables_22
product_vegetables_23
product_vegetables_24
product_vegetables_25
product_vegetables_26
product_vegetables_27
product_vegetables_28
product_vegetables_29
product_vegetables_30
product_vegetables_31
product_vegetables_32
product_vegetables_33
product_vegetables_34
product_vegetables_35
product_vegetables_36
product_vegetables_37
product_vegetables_38
product_vegetables_39
product_vegetables_40
product_vegetables_41
product_vegetables_42
product_vegetables_43
product_vegetables_44
product_vegetables_45
product_vegetables_46
product_vegetables_47
product_vegetables_48
product_vegetables_49
product_vegetables_50
product_vegetables_51
product_vegetables_52
product_vegetables_53
product_vegetables_54
product_vegetables_55
product_vegetables_56
product_vegetables_57
product_vegetables_888
product_vegetables_otherdesc
product_fishseafood
product_fishseafood_1
product_fishseafood_2
product_fishseafood_3
product_fishseafood_4
product_fishseafood_5
product_fishseafood_6
product_fishseafood_7
product_fishseafood_8
product_fishseafood_888
product_fishseafood_otherdesc
product_poultryfowl
product_poultryfowl_1
product_poultryfowl_2
product_poultryfowl_3
product_poultryfowl_4
product_poultryfowl_5
product_poultryfowl_6
product_poultryfowl_7
product_poultryfowl_8
product_poultryfowl_9
product_poultryfowl_888
product_poultryfowl_otherdesc
product_redmeat
product_redmeat_1
product_redmeat_2
product_redmeat_3
product_redmeat_4
product_redmeat_5
product_redmeat_6
product_redmeat_7
product_redmeat_8
product_redmeat_9
product_redmeat_10
product_redmeat_11
product_redmeat_12
product_redmeat_13
product_redmeat_14
product_redmeat_15
product_redmeat_16
product_redmeat_17
product_redmeat_18
product_redmeat_888
product_redmeat_otherdesc
products_otherdesc
share_number
share_size
share_size_1
share_size_2
share_size_888
share_size_otherdesc
share_itemsinsharebox
share_itemsinsharebox_1
share_itemsinsharebox_2
share_itemsinsharebox_3
share_itemsinsharebox_888
share_itemsinsharebox_otherdesc
share_availabledate
share_paymentoption
share_paymentoption_1
share_paymentoption_2
share_paymentoption_3
share_paymentoption_4
share_paymentoption_888
share_paymentoption_otherdesc
deliverpickup_method
deliverpickup_method_1
deliverpickup_method_2
deliverpickup_method_3
deliverpickup_method_4
deliverpickup_method_888
deliverpickup_method_otherdesc
specialproductionmethods
specialproductionmethods_1
specialproductionmethods_2
specialproductionmethods_3
specialproductionmethods_4
specialproductionmethods_5
specialproductionmethods_6
specialproductionmethods_7
specialproductionmethods_8
specialproductionmethods_9
specialproductionmethods_10
specialproductionmethods_11
specialproductionmethods_12
specialproductionmethods_13
specialproductionmethods_14
specialproductionmethods_888
specialproductionmethods_other_desc
acceptedpayment
acceptedpayment_1
acceptedpayment_2
acceptedpayment_3
acceptedpayment_4
acceptedpayment_5
acceptedpayment_6
acceptedpayment_7
acceptedpayment_888
acceptedpayment_7_desc
acceptedpayment_other_desc
FNAP
FNAP_1
FNAP_2
FNAP_3
FNAP_888
FNAP_3_desc
FNAP_other_desc
webscripting
bulktable_id
bulktable_row_id
index_right
MTFCC
OID
GEOID
STATE
COUNTY
COUNTYNS
BASENAME
NAME
LSADC
FUNCSTAT
COUNTYCC
AREALAND
AREAWATER
OBJECTID
CENTLAT
CENTLON
INTPTLAT
INTPTLON
geometry

In [6]:
gdf[["location_x", "location_y"]].head()

   location_x  location_y
0  -96.872630   32.862163
1  -97.654769   30.236938
2  -97.562789   30.260666
3  -97.556946   30.340763
4  -97.634880   30.285748

In [10]:
df = gdf[[
    "listing_name",
    "location_address",
    "location_y",
    "location_x",
    "OID",
    "GEOID",
    "STATE",
    "COUNTY"
]].copy()

df = df.rename(columns={
    "listing_name": "name",
    "location_address": "address",
    "location_y": "latitude",
    "location_x": "longitude",
    "STATE": "state",
    "COUNTY": "county",
    "OID": "oid",
    "GEOID": "geoid"
})

In [11]:
df.to_csv("usda_ofm.csv")

In [17]:
gdf1 = gpd.read_file("../dallasFarmsFinal.geojson")

In [18]:
print(gdf1.columns)

Index(['SiteName', 'Address', 'geometry'], dtype='object')

In [23]:
gdf1["longitude"] = gdf1.geometry.x
gdf1["latitude"] = gdf1.geometry.y

df = gdf1[[
    "SiteName",
    "Address",
    "latitude",
    "longitude"
]].copy()

df = df.rename(columns={
    "SiteName": "name",
    "Address": "address"
})

df["state"] = None
df["county"] = None

df.to_csv("cleaned_dallas_geojson.csv", index=False)